In [2]:
import pandas as pd

df = pd.read_csv('../data/listings.csv')
print(df.shape)
df.head()

(15293, 90)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,18674,https://www.airbnb.com/rooms/18674,20260624162917,2026-06-25,city scrape,Huge flat for 8 people close to Sagrada Familia,110m2 apartment to rent in Barcelona. Located ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,71615,...,4.64,4.83,4.38,Spain - National registration number<br />ESFC...,NaN,20,20,0,0,0.37
1,23197,https://www.airbnb.com/rooms/23197,20260624162917,2026-06-25,city scrape,CCIB Forum· Large Balcony · 5 min walk to CCIB,"Beautiful, spacious apartment with large balco...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,90417,...,4.99,4.69,4.71,Spain - National registration number<br />ESFC...,NaN,1,1,0,0,0.53
2,34981,https://www.airbnb.com/rooms/34981,20260624162917,2026-06-25,city scrape,VIDRE HOME PLAZA REAL on LAS RAMBLAS,Spacious apartment for large families or group...,NaN,https://a0.muscache.com/pictures/c4d1723c-e479...,73163,...,4.75,4.65,4.48,Spain - National registration number<br />ESFC...,NaN,2,2,0,0,1.59
3,36763,https://www.airbnb.com/rooms/36763,20260624162917,2026-07-03,previous scrape,In front of the beach,NaN,NaN,https://a0.muscache.com/pictures/airflow/Hosti...,158596,...,4.92,4.92,4.82,NaN,NaN,1,0,1,0,0.60
4,40983,https://www.airbnb.com/rooms/40983,20260624162917,2026-06-25,city scrape,Architect's Loft near Gaudí & Passeig de Gràcia,Stay in a charming architect-designed loft in ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,177617,...,4.86,4.91,4.52,Barcelona - Regional registration number<br />...,NaN,5,2,3,0,2.46

In [3]:
print(df.columns.tolist())

['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months', 'hosts_time_as_host_years', 'hosts_time_as_host_months', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'price_quote_checkin_date', 'price_quote_checkout_date', 'price_quote_total_price', 'price_quote_price_per_night', 'price_quote_raw', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month']

In [5]:
key_columns = [
    'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude',
    'property_type', 'room_type', 'accommodates', 'bedrooms', 'beds',
    'price', 'minimum_nights', 'availability_365',
    'number_of_reviews', 'review_scores_rating', 'host_is_superhost',
    'estimated_occupancy_l365d', 'estimated_revenue_l365d'
]

print(df[key_columns].isnull().sum())
print()
print(df[key_columns].dtypes)

neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bedrooms                        2562
beds                            2447
price                           1938
minimum_nights                     1
availability_365                   0
number_of_reviews                  0
review_scores_rating            3548
host_is_superhost                 87
estimated_occupancy_l365d          0
estimated_revenue_l365d         1938
dtype: int64

neighbourhood_cleansed           object
neighbourhood_group_cleansed     object
latitude                        float64
longitude                       float64
property_type                    object
room_type                        object
accommodates                      int64
bedrooms                        float64
beds                            float64
price                            object
minimum_nights                  float64
availability_365                  int64
number_of_reviews                 int64
review_scores_rating            float64
host_is_superhost                object
estimated_occupancy_l365d         int64
estimated_revenue_l365d         float64
dtype: object

In [6]:
print(df['price'].head(10))
print(df['price'].dtype)

0    $409.00
1    $388.00
2    $397.13
3     $43.24
4    $226.13
5        NaN
6    $417.80
7    $275.50
8    $107.61
9    $209.00
Name: price, dtype: object
object

In [7]:
print(df['neighbourhood_cleansed'].unique())

['la Sagrada Família' 'el Besòs i el Maresme' 'el Barri Gòtic'
 'la Barceloneta' "la Dreta de l'Eixample"
 "el Camp d'en Grassot i Gràcia Nova" 'Vallcarca i els Penitents'
 'el Raval' 'el Poblenou' 'el Clot' 'el Poble Sec' 'Pedralbes'
 'Sant Antoni' 'Sant Pere, Santa Caterina i la Ribera' 'el Guinardó'
 "l'Antiga Esquerra de l'Eixample"
 'Diagonal Mar i el Front Marítim del Poblenou' 'la Vila de Gràcia'
 'el Fort Pienc' 'Sant Martí de Provençals'
 "la Nova Esquerra de l'Eixample" 'Sarrià'
 'el Parc i la Llacuna del Poblenou' 'la Vila Olímpica del Poblenou'
 'les Corts' 'el Putxet i el Farró' 'Sant Gervasi - Galvany'
 'el Congrés i els Indians' 'el Baix Guinardó' 'Navas' 'la Bordeta'
 'Sants' 'Vilapicina i la Torre Llobeta' 'la Prosperitat'
 'Provençals del Poblenou' 'Sants - Badal' 'la Maternitat i Sant Ramon'
 'el Carmel' 'Hostafrancs' 'la Salut' 'Sant Gervasi - la Bonanova'
 'les Tres Torres' 'Vallvidrera, el Tibidabo i les Planes' 'la Teixonera'
 'Can Baró' "el Camp de l'Arpa del Clot" 'la Marina del Prat Vermell'
 'el Coll' 'la Verneda i la Pau' 'Porta' 'la Font de la Guatlla'
 'la Sagrera' 'Sant Andreu' "la Font d'en Fargues" 'la Marina de Port'
 'la Guineueta' 'Horta' "la Vall d'Hebron" 'el Turó de la Peira' 'Montbau'
 'el Bon Pastor' 'la Trinitat Vella' 'les Roquetes' 'Verdun' 'la Clota'
 'Sant Genís dels Agudells' 'la Trinitat Nova' 'Torre Baró'
 'Ciutat Meridiana']

In [8]:
print(df['neighbourhood_group_cleansed'].unique())

['Eixample' 'Sant Martí' 'Ciutat Vella' 'Gràcia' 'Sants-Montjuïc'
 'Les Corts' 'Horta-Guinardó' 'Sarrià-Sant Gervasi' 'Sant Andreu'
 'Nou Barris']

In [9]:
# Clean price: strip $ and comma, convert to float
df['price_clean'] = df['price'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

print(df['price_clean'].describe())
print("Nulls:", df['price_clean'].isnull().sum())

count    13355.000000
mean       240.616470
std        339.474553
min          3.500000
25%         89.290000
50%        177.670000
75%        285.500000
max      10542.220000
Name: price_clean, dtype: float64
Nulls: 1938

In [10]:
# Check what's going on with null-price listings
null_price = df[df['price_clean'].isnull()]
print(null_price['has_availability'].value_counts())
print(null_price['availability_365'].describe())

has_availability
t    1858
f      12
Name: count, dtype: int64
count    1938.000000
mean       39.642415
std        93.484348
min         0.000000
25%         0.000000
50%         0.000000
75%         8.000000
max       365.000000
Name: availability_365, dtype: float64

In [11]:
client_districts = ['Eixample', 'Gràcia', 'Ciutat Vella']
df['client_district'] = df['neighbourhood_group_cleansed'].isin(client_districts)

print(df['client_district'].value_counts())

client_district
True     10448
False     4845
Name: count, dtype: int64

In [12]:
df['host_is_superhost'] = df['host_is_superhost'].map({'t': True, 'f': False})
print(df['host_is_superhost'].value_counts(dropna=False))

host_is_superhost
False    11274
True      3932
NaN         87
Name: count, dtype: int64

In [13]:
# Drop rows with no price (not analyzable for pricing purposes)
df_clean = df[df['price_clean'].notnull()].copy()
print("Rows after dropping null prices:", df_clean.shape[0])

# Check room_type breakdown - we care about entire apartments (Marisol's unit type)
print(df_clean['room_type'].value_counts())

Rows after dropping null prices: 13355
room_type
Entire home/apt    10114
Private room        3082
Shared room           97
Hotel room            62
Name: count, dtype: int64

In [14]:
df_clean['is_entire_apt'] = df_clean['room_type'] == 'Entire home/apt'
print(df_clean['is_entire_apt'].value_counts())

# Check for price outliers - that max of $10,542/night looks suspicious
print(df_clean['price_clean'].sort_values(ascending=False).head(20))

is_entire_apt
True     10114
False     3241
Name: count, dtype: int64
8077     10542.22
12321     7532.00
12139     7293.00
12155     6151.00
12112     6106.00
10137     5900.00
11240     4885.00
8356      4463.00
11224     4394.00
12859     4080.00
13567     3983.00
4869      3858.00
10805     3766.00
12274     3698.00
11125     3664.00
11142     3664.00
10081     3664.00
9256      3664.00
12289     3652.00
13406     3629.00
Name: price_clean, dtype: float64

In [15]:
print(df_clean['price_clean'].sort_values().head(20))

4403      3.50
8337      6.88
3709      9.07
8409      9.18
157       9.62
5905      9.85
5346     10.95
10594    11.06
3704     11.85
9451     11.96
5225     11.99
9452     12.31
8449     12.42
1583     12.56
188      12.87
9449     13.14
1301     13.20
4623     13.37
6811     13.58
3057     13.83
Name: price_clean, dtype: float64

In [16]:
high_price = df_clean.sort_values('price_clean', ascending=False).head(10)
print(high_price[['name', 'room_type', 'accommodates', 'bedrooms', 'price_clean', 'neighbourhood_group_cleansed']])

                                                    name        room_type  \
8077         Amazing loft-style apartment in Las Ramblas  Entire home/apt
12321  Elegant 12-bedr GroupFlat with 12-bathr 24 people  Entire home/apt
12139  Elegant 12-bedr GroupFlat with 12-bathr 24 people  Entire home/apt
12155  Acomodis • Groups • Up to 27 Guests • Ask for ...  Entire home/apt
12112  GroupFlat 15-Bedr 10-Bath next Casa Batlló 35 ppl  Entire home/apt
10137  Just 10 minutes from Casa Batlló Gaudi - 22 pe...  Entire home/apt
11240  GroupFlat 12-Bed 8-Bath next Casa Batlló 28people  Entire home/apt
8356        Modern Apartment With Balcony In Lively Area  Entire home/apt
11224    Great GroupFlat 15-bed 10-bath Eixample 30 ppl!  Entire home/apt
12859  Nice 15-Bedroom 10-Bath near Pl. Catalunya 30 ppl  Entire home/apt

       accommodates  bedrooms  price_clean neighbourhood_group_cleansed
8077              2       1.0     10542.22                 Ciutat Vella
12321            16      12.0      7532.00                     Eixample
12139            16      12.0      7293.00                     Eixample
12155            16      14.0      6151.00                     Eixample
12112            16      15.0      6106.00                     Eixample
10137            16      10.0      5900.00                     Eixample
11240            16      12.0      4885.00                     Eixample
8356              4       2.0      4463.00                     Eixample
11224            16      15.0      4394.00                     Eixample
12859            16      15.0      4080.00                 Ciutat Vella

In [17]:
low_price = df_clean.sort_values('price_clean').head(10)
print(low_price[['name', 'room_type', 'accommodates', 'bedrooms', 'price_clean', 'neighbourhood_group_cleansed']])

                                                    name        room_type  \
4403                               Zalupka pupka zalupka     Private room
8337       Excelente departamento muy cerca de la playa!  Entire home/apt
3709   Charming apartment in the nice El Clot, long s...  Entire home/apt
8409                      Barcelona Sagrada Familia - H2     Private room
157                          FURNISED   ROOM   FOR  RENT     Private room
5905     Beautiful beach apartment in downtown Barcelona  Entire home/apt
5346   A Double room with private bathroom in the center     Private room
10594                               apartamento acogedor  Entire home/apt
3704         Habitación individual. Baño privado. Jardín     Private room
9451                      Barcelona Sagrada Familia - H4     Private room

       accommodates  bedrooms  price_clean neighbourhood_group_cleansed
4403              1       NaN         3.50               Sants-Montjuïc
8337              2       1.0         6.88                 Ciutat Vella
3709              3       2.0         9.07                   Sant Martí
8409              1       NaN         9.18                   Sant Martí
157               1       NaN         9.62                   Nou Barris
5905              2       1.0         9.85                 Ciutat Vella
5346              2       NaN        10.95                     Eixample
10594             2       1.0        11.06               Horta-Guinardó
3704              1       NaN        11.85                       Gràcia
9451              1       NaN        11.96                   Sant Martí

In [18]:
# Remove the one clear price data error (1BR/2-guest loft at $10,542/night)
df_clean = df_clean[df_clean['price_clean'] < 10000].copy()
print("Rows after removing extreme outlier:", df_clean.shape[0])

Rows after removing extreme outlier: 13354

In [19]:
df_clean.to_csv('../data/listings_cleaned.csv', index=False)
print("Saved listings_cleaned.csv")
print(df_clean.shape)

Saved listings_cleaned.csv
(13354, 93)

In [20]:
relevant_cols = [
    'id', 'name', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed',
    'latitude', 'longitude', 'property_type', 'room_type', 'is_entire_apt',
    'client_district', 'accommodates', 'bedrooms', 'beds', 'price_clean',
    'minimum_nights', 'availability_365', 'number_of_reviews',
    'review_scores_rating', 'host_is_superhost', 'estimated_occupancy_l365d',
    'estimated_revenue_l365d'
]

df_sql = df_clean[relevant_cols].copy()
df_sql.to_csv('../data/listings_for_sql.csv', index=False)
print(df_sql.shape)
df_sql.head()

(13354, 21)

,id,name,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,is_entire_apt,client_district,...,bedrooms,beds,price_clean,minimum_nights,availability_365,number_of_reviews,review_scores_rating,host_is_superhost,estimated_occupancy_l365d,estimated_revenue_l365d
0,18674,Huge flat for 8 people close to Sagrada Familia,la Sagrada Família,Eixample,41.405560,2.17262,Entire rental unit,Entire home/apt,True,True,...,3.0,5.0,409.00,1.0,123,59,4.41,False,54,22086.0
1,23197,CCIB Forum· Large Balcony · 5 min walk to CCIB,el Besòs i el Maresme,Sant Martí,41.412432,2.21975,Entire rental unit,Entire home/apt,True,False,...,3.0,4.0,388.00,2.0,239,99,4.84,True,66,25608.0
2,34981,VIDRE HOME PLAZA REAL on LAS RAMBLAS,el Barri Gòtic,Ciutat Vella,41.379780,2.17623,Entire rental unit,Entire home/apt,True,True,...,4.0,6.0,397.13,1.0,329,304,4.59,True,222,88163.0
3,36763,In front of the beach,la Barceloneta,Ciutat Vella,41.380370,2.19272,Private room in rental unit,Private room,False,True,...,NaN,NaN,43.24,31.0,38,108,4.79,False,0,0.0
4,40983,Architect's Loft near Gaudí & Passeig de Gràcia,la Dreta de l'Eixample,Eixample,41.396310,2.16832,Entire condo,Entire home/apt,True,True,...,1.0,2.0,226.13,1.0,289,450,4.56,True,255,57663.0

In [21]:
import os
print(os.path.exists('../data/listings_for_sql.csv'))
print(os.path.getsize('../data/listings_for_sql.csv') / 1024, "KB")

True
2617.470703125 KB

In [ ]:
import os
print(os.path.exists('../data/listings_for_sql.csv'))
print(os.path.getsize('../data/listings_for_sql.csv') / 1024, "KB")

True
2617.470703125 KB